import type { Product, Category, Stream, Auction } from "@/types/database";

export const categories: Category[] = [
  { id: "1", name: "Streetwear", slug: "streetwear", description: "Bold street style for the culture", image: null, parent_id: null },
  { id: "2", name: "Vintage", slug: "vintage", description: "Rare finds from past decades", image: null, parent_id: null },
  { id: "3", name: "Sneakers", slug: "sneakers", description: "Limited drops and grails", image: null, parent_id: null },
  { id: "4", name: "Trading Card Games", slug: "trading-card-games", description: "Pokemon, Magic, Yu-Gi-Oh and more", image: null, parent_id: null },
  { id: "5", name: "Sports Cards", slug: "sports-cards", description: "NBA, UFC, Football collectibles", image: null, parent_id: null },
  { id: "6", name: "Activewear", slug: "activewear", description: "Performance meets style", image: null, parent_id: null },
  { id: "7", name: "Accessories", slug: "accessories", description: "Caps, bags, jewelry and more", image: null, parent_id: null },
  { id: "8", name: "Toys & Collectibles", slug: "toys-collectibles", description: "Funko Pops, figures, and rare collectibles", image: null, parent_id: null },
];

export const products: Product[] = [
  {
    id: "p1",
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2025-01-15T10:00:00Z",
    title: "LVL x Dubai Oversized Tee",
    slug: "lvl-dubai-oversized-tee",
    description: "Limited edition oversized tee from the LVL Dubai drop. Premium heavyweight cotton with screen-printed graphics. This drop won't wait. Neither should you.",
    price: 289,
    compare_at_price: 350,
    currency: "AED",
    category_id: "1",
    brand: "LET'S LVL",
    images: [
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=1000&fit=crop",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White"],
    tags: ["new-arrival", "limited-edition"],
    inventory_count: 45,
    is_featured: true,
    is_live_exclusive: false,
    seller_id: "s1",
    status: "active",
  },
  {
    id: "p2",
    created_at: "2025-01-14T10:00:00Z",
    updated_at: "2025-01-14T10:00:00Z",
    title: "Air Jordan 4 Retro 'Thunder'",
    slug: "air-jordan-4-retro-thunder",
    description: "The Air Jordan 4 Retro 'Thunder' returns with its iconic black and yellow colorway. Tour Yellow accents on a black nubuck upper.",
    price: 1299,
    compare_at_price: null,
    currency: "AED",
    category_id: "3",
    brand: "Nike",
    images: [
      "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&h=1000&fit=crop",
    ],
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: ["Black/Yellow"],
    tags: ["sneakers", "jordan"],
    inventory_count: 12,
    is_featured: true,
    is_live_exclusive: false,
    seller_id: "s2",
    status: "active",
  },
  {
    id: "p3",
    created_at: "2025-01-13T10:00:00Z",
    updated_at: "2025-01-13T10:00:00Z",
    title: "Vintage 90s Racing Jacket",
    slug: "vintage-90s-racing-jacket",
    description: "Authentic 90s vintage racing jacket. All-over graphic print with embroidered patches. One of a kind.",
    price: 549,
    compare_at_price: 699,
    currency: "AED",
    category_id: "2",
    brand: "Vintage",
    images: [
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=1000&fit=crop",
    ],
    sizes: ["M", "L", "XL"],
    colors: ["Multi"],
    tags: ["vintage", "rare"],
    inventory_count: 3,
    is_featured: true,
    is_live_exclusive: false,
    seller_id: "s3",
    status: "active",
  },
  {
    id: "p4",
    created_at: "2025-01-12T10:00:00Z",
    updated_at: "2025-01-12T10:00:00Z",
    title: "Pokemon Scarlet & Violet Booster Box",
    slug: "pokemon-sv-booster-box",
    description: "Sealed Pokemon Scarlet & Violet base set booster box. 36 packs. Hunt for rare illustration cards.",
    price: 799,
    compare_at_price: null,
    currency: "AED",
    category_id: "4",
    brand: "Pokemon",
    images: [
      "https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=800&h=1000&fit=crop",
    ],
    sizes: [],
    colors: [],
    tags: ["pokemon", "sealed", "tcg"],
    inventory_count: 8,
    is_featured: false,
    is_live_exclusive: true,
    seller_id: "s4",
    status: "active",
  },
  {
    id: "p5",
    created_at: "2025-01-11T10:00:00Z",
    updated_at: "2025-01-11T10:00:00Z",
    title: "Essentials Fear of God Hoodie",
    slug: "essentials-fog-hoodie",
    description: "Fear of God Essentials oversized hoodie. Signature rubber logo on chest. Heavyweight fleece.",
    price: 459,
    compare_at_price: 520,
    currency: "AED",
    category_id: "1",
    brand: "Fear of God",
    images: [
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&h=1000&fit=crop",
      "https://images.unsplash.com/photo-1578768079470-4deaf7e30215?w=800&h=1000&fit=crop",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Dark Oatmeal", "Black", "Cement"],
    tags: ["essentials", "hoodie"],
    inventory_count: 22,
    is_featured: true,
    is_live_exclusive: false,
    seller_id: "s1",
    status: "active",
  },
  {
    id: "p6",
    created_at: "2025-01-10T10:00:00Z",
    updated_at: "2025-01-10T10:00:00Z",
    title: "NBA Panini Prizm Blaster Box",
    slug: "nba-panini-prizm-blaster",
    description: "2024-25 Panini Prizm NBA Basketball Blaster Box. Chase rookie cards and rare prizm parallels.",
    price: 349,
    compare_at_price: null,
    currency: "AED",
    category_id: "5",
    brand: "Panini",
    images: [
      "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=1000&fit=crop",
    ],
    sizes: [],
    colors: [],
    tags: ["sports-cards", "nba", "panini"],
    inventory_count: 15,
    is_featured: false,
    is_live_exclusive: false,
    seller_id: "s4",
    status: "active",
  },
  {
    id: "p7",
    created_at: "2025-01-09T10:00:00Z",
    updated_at: "2025-01-09T10:00:00Z",
    title: "Stussy x Nike Air Force 1 Low",
    slug: "stussy-nike-af1-low",
    description: "Stussy x Nike Air Force 1 Low collaboration. Hand-dyed upper with Stussy branding. Limited release.",
    price: 1099,
    compare_at_price: 1399,
    currency: "AED",
    category_id: "3",
    brand: "Nike x Stussy",
    images: [
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&h=1000&fit=crop",
    ],
    sizes: ["40", "41", "42", "43", "44"],
    colors: ["Fossil Stone"],
    tags: ["sneakers", "collab", "limited"],
    inventory_count: 5,
    is_featured: true,
    is_live_exclusive: false,
    seller_id: "s2",
    status: "active",
  },
  {
    id: "p8",
    created_at: "2025-01-08T10:00:00Z",
    updated_at: "2025-01-08T10:00:00Z",
    title: "Chrome Hearts Trucker Cap",
    slug: "chrome-hearts-trucker-cap",
    description: "Authentic Chrome Hearts trucker cap with leather cross patch. Adjustable snapback.",
    price: 1850,
    compare_at_price: null,
    currency: "AED",
    category_id: "7",
    brand: "Chrome Hearts",
    images: [
      "https://images.unsplash.com/photo-1588850561407-ed78c334e67a?w=800&h=1000&fit=crop",
    ],
    sizes: ["One Size"],
    colors: ["Black"],
    tags: ["accessories", "luxury"],
    inventory_count: 2,
    is_featured: false,
    is_live_exclusive: true,
    seller_id: "s3",
    status: "active",
  },
];

export const streams: Stream[] = [
  {
    id: "st1",
    created_at: "2025-03-27T10:00:00Z",
    seller_id: "s4",
    seller: { full_name: "Pop Haven QA", avatar_url: null },
    title: "One Piece TCG singles & sealed items + Dragon Ball TCG",
    description: "Pop Haven Short Live Streaming. One piece TCG singles & sealed items. Dragon ball TCG singles & sealed items. Funko pops (Anime, Marvel, DC, Disney)",
    category: "Trading Card Games",
    thumbnail_url: "https://images.unsplash.com/photo-1608889825103-eb5ed706fc19?w=600&h=400&fit=crop",
    status: "live",
    viewer_count: 2400,
    stream_url: null,
    scheduled_at: null,
    started_at: "2025-03-27T14:00:00Z",
    ended_at: null,
    country_flag: "QA",
  },
  {
    id: "st2",
    created_at: "2025-03-27T11:00:00Z",
    seller_id: "s5",
    seller: { full_name: "AECollector", avatar_url: null },
    title: "New Pokemon set release - ETB, Packs, Booster Boxes",
    description: "New Pokemon set release! Perfect order. ETB, Packs, BB available.",
    category: "Trading Card Games",
    thumbnail_url: "https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=600&h=400&fit=crop",
    status: "live",
    viewer_count: 1850,
    stream_url: null,
    scheduled_at: null,
    started_at: "2025-03-27T14:30:00Z",
    ended_at: null,
    country_flag: "AE",
  },
  {
    id: "st3",
    created_at: "2025-03-27T08:00:00Z",
    seller_id: "s1",
    seller: { full_name: "StreetKingz Dubai", avatar_url: null },
    title: "Vintage Jordan drop + Essentials restock",
    description: "Massive vintage Jordan collection drop. Fear of God Essentials restock. Live bidding on rare pieces.",
    category: "Fashion",
    thumbnail_url: "https://images.unsplash.com/photo-1556906781-9a412961c28c?w=600&h=400&fit=crop",
    status: "live",
    viewer_count: 3200,
    stream_url: null,
    scheduled_at: null,
    started_at: "2025-03-27T13:00:00Z",
    ended_at: null,
    country_flag: "AE",
  },
  {
    id: "st4",
    created_at: "2025-03-27T12:00:00Z",
    seller_id: "s6",
    seller: { full_name: "SaudiSneakerHead", avatar_url: null },
    title: "Nike Dunk SB collection - rare colorways",
    description: "Massive Nike Dunk SB collection. Rare colorways you won't find anywhere else. Live auctions starting at 100 SAR.",
    category: "Fashion",
    thumbnail_url: "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=600&h=400&fit=crop",
    status: "scheduled",
    viewer_count: 0,
    stream_url: null,
    scheduled_at: "2025-03-27T18:00:00Z",
    started_at: null,
    ended_at: null,
    country_flag: "SA",
  },
  {
    id: "st5",
    created_at: "2025-03-26T10:00:00Z",
    seller_id: "s7",
    seller: { full_name: "UFC Cards ME", avatar_url: null },
    title: "UFC Prizm breaks + Basketball cards auction",
    description: "UFC Prizm card breaks live. Basketball rookies auction. High-value pulls guaranteed.",
    category: "Sports Cards",
    thumbnail_url: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&h=400&fit=crop",
    status: "live",
    viewer_count: 980,
    stream_url: null,
    scheduled_at: null,
    started_at: "2025-03-27T15:00:00Z",
    ended_at: null,
    country_flag: "AE",
  },
];

export const auctions: Auction[] = [
  {
    id: "a1",
    stream_id: "st3",
    product_id: "p2",
    product: products[1],
    start_price: 500,
    current_bid: 850,
    bid_increment: 50,
    currency: "AED",
    status: "active",
    winner_id: null,
    end_time: new Date(Date.now() + 180000).toISOString(),
    bid_count: 14,
  },
  {
    id: "a2",
    stream_id: "st1",
    product_id: "p4",
    product: products[3],
    start_price: 300,
    current_bid: 620,
    bid_increment: 25,
    currency: "AED",
    status: "active",
    winner_id: null,
    end_time: new Date(Date.now() + 90000).toISOString(),
    bid_count: 22,
  },
];
